-- Update public.juniors.region from the Juniors sheet in master data.
-- Master values are converted from Japanese labels to kanto/kansai.

BEGIN;

CREATE TEMP TABLE junior_region_master (
    name text PRIMARY KEY,
    region text NOT NULL CHECK (region IN ('kanto', 'kansai'))
) ON COMMIT DROP;

INSERT INTO junior_region_master (name, region)
VALUES
    ('アンダーソンフェニックス', 'kanto'),
    ('デービスジョシュ', 'kansai'),
    ('ヴァサイェガ渉', 'kanto'),
    ('三原健豊', 'kanto'),
    ('三浦慎ノ亮', 'kansai'),
    ('上垣廣祐', 'kansai'),
    ('上田凱吏', 'kansai'),
    ('中崎結翔', 'kansai'),
    ('中川亜音', 'kansai'),
    ('中川惺太', 'kansai'),
    ('中本輝', 'kansai'),
    ('中村嶺亜', 'kanto'),
    ('中村浩大', 'kanto'),
    ('中野英司', 'kansai'),
    ('中須賀湊登', 'kansai'),
    ('丸岡晃聖', 'kansai'),
    ('久保廉', 'kanto'),
    ('亀井海聖', 'kansai'),
    ('亀井碧空', 'kansai'),
    ('井上一太', 'kansai'),
    ('井上瑞稀', 'kanto'),
    ('井上蒼生', 'kansai'),
    ('今江翔', 'kansai'),
    ('今野大輝', 'kanto'),
    ('仲田慎平', 'kansai'),
    ('伊藤篤志', 'kansai'),
    ('伯井太陽', 'kansai'),
    ('佐々木大光', 'kanto'),
    ('佐藤凛空', 'kansai'),
    ('佐藤龍我', 'kanto'),
    ('佐野斗真', 'kanto'),
    ('作間龍斗', 'kanto'),
    ('元木湧', 'kanto'),
    ('元重瑛翔', 'kansai'),
    ('内村颯太', 'kanto'),
    ('内田煌音', 'kanto'),
    ('出雲颯空', 'kanto'),
    ('北川拓実', 'kanto'),
    ('北村仁太郎', 'kansai'),
    ('北野快浬', 'kansai'),
    ('千井野空翔', 'kanto'),
    ('千田藍生', 'kansai'),
    ('和田優希', 'kanto'),
    ('堀口由翔', 'kanto'),
    ('塩山直太朗', 'kansai'),
    ('壹岐碧', 'kanto'),
    ('大内リオン', 'kansai'),
    ('大田蒼空', 'kansai'),
    ('大西風雅', 'kansai'),
    ('安嶋秀生', 'kanto'),
    ('宮岡大愛', 'kanto'),
    ('宮部敬太', 'kanto'),
    ('宮部聡太', 'kanto'),
    ('小久保向一朗', 'kanto'),
    ('小尾颯', 'kansai'),
    ('小山十輝', 'kanto'),
    ('小松原頼安', 'kanto'),
    ('小森ラリマール世界', 'kanto'),
    ('山上瑠偉', 'kansai'),
    ('山中一輝', 'kansai'),
    ('山井飛翔', 'kanto'),
    ('山岸想', 'kanto'),
    ('山崎旺夏', 'kanto'),
    ('山庄司蒼偉', 'kansai'),
    ('山田輝虎', 'kansai'),
    ('岡佑吏', 'kansai'),
    ('岡夢人', 'kansai'),
    ('岡橋亮汰', 'kanto'),
    ('岡田耕明', 'kansai'),
    ('岡野すこやか', 'kansai'),
    ('岡﨑彪太郎', 'kansai'),
    ('岩倉司', 'kansai'),
    ('岩崎楓士', 'kanto'),
    ('岩﨑大昇', 'kanto'),
    ('岸蒼太', 'kanto'),
    ('嵜本孝太朗', 'kansai'),
    ('嶋﨑斗亜', 'kansai'),
    ('川上楓愛', 'kansai'),
    ('川口拓馬', 'kansai'),
    ('川津レオン', 'kanto'),
    ('川﨑星輝', 'kanto'),
    ('川﨑皇輝', 'kanto'),
    ('平田光寛', 'kanto'),
    ('廣末裕理', 'kansai'),
    ('新宮楓真', 'kanto'),
    ('末永光', 'kanto'),
    ('本高克樹', 'kanto'),
    ('松尾龍', 'kanto'),
    ('松浦栞大', 'kanto'),
    ('松浦銀志', 'kanto'),
    ('林田芯', 'kanto'),
    ('林蓮音', 'kanto'),
    ('染谷樹', 'kanto'),
    ('梨子木憐', 'kanto'),
    ('森ケイン', 'kansai'),
    ('横田大都', 'kanto'),
    ('橋本涼', 'kanto'),
    ('橋本誠吾', 'kansai'),
    ('檜山光成', 'kanto'),
    ('永岡蓮王', 'kansai'),
    ('江口煌真', 'kanto'),
    ('池川侑希弥', 'kansai'),
    ('池田陸斗', 'kansai'),
    ('浅井乃我', 'kanto'),
    ('浦陸斗', 'kansai'),
    ('浮所飛貴', 'kanto'),
    ('深田竜生', 'kanto'),
    ('渡辺惟良', 'kanto'),
    ('渡邉大我', 'kansai'),
    ('濱出顕斗', 'kansai'),
    ('瀬川嵐太', 'kansai'),
    ('猪狩蒼弥', 'kanto'),
    ('玉城流衣', 'kanto'),
    ('田代海琉', 'kanto'),
    ('田仲陽成', 'kanto'),
    ('田口寛晃', 'kanto'),
    ('田村海琉', 'kanto'),
    ('田﨑駿斗', 'kansai'),
    ('真弓孟之', 'kansai'),
    ('真虎', 'kanto'),
    ('矢花黎', 'kanto'),
    ('稲葉通陽', 'kanto'),
    ('竹村実悟', 'kanto'),
    ('竹田湊', 'kanto'),
    ('笹田陽之介', 'kansai'),
    ('織山尚大', 'kanto'),
    ('羽村仁成', 'kanto'),
    ('菅田琳寧', 'kanto'),
    ('藤本有惺', 'kansai'),
    ('藤田真暢', 'kansai'),
    ('西中秀太', 'kanto'),
    ('西原至', 'kanto'),
    ('西巻染', 'kanto'),
    ('西村拓哉', 'kansai'),
    ('西野湊人', 'kansai'),
    ('西野統真', 'kansai'),
    ('角紳太郎', 'kansai'),
    ('谷口尊星', 'kansai'),
    ('豊田陸人', 'kanto'),
    ('那須雄登', 'kanto'),
    ('野母一晟', 'kansai'),
    ('野田開仁', 'kansai'),
    ('鈴木悠仁', 'kanto'),
    ('鈴木瑛朝', 'kanto'),
    ('鍋田大成', 'kanto'),
    ('長瀬結星', 'kanto'),
    ('関翔馬', 'kanto'),
    ('阿達慶', 'kanto'),
    ('青木滉平', 'kanto'),
    ('馬場律樹', 'kanto'),
    ('高橋奏琉', 'kanto'),
    ('高橋礼', 'kanto'),
    ('髙谷弦汰', 'kanto'),
    ('鳥居桜丞', 'kanto'),
    ('黒田光輝', 'kanto');

DO $$
DECLARE
    v_missing_count integer;
BEGIN
    SELECT COUNT(*)
    INTO v_missing_count
    FROM junior_region_master AS master
    LEFT JOIN public.juniors AS juniors
        ON juniors.name = master.name
    WHERE juniors.id IS NULL;

    IF v_missing_count > 0 THEN
        RAISE EXCEPTION 'juniors.region update has % names that do not exist in public.juniors', v_missing_count;
    END IF;
END;
$$;

UPDATE public.juniors AS juniors
SET region = master.region
FROM junior_region_master AS master
WHERE juniors.name = master.name;

COMMIT;
